version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www/

  # The Web Server
  web:
    build:
      context: ./docker/web/
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./docker/web/:/var/www/
      - ./public:/var/www/public
    ports:
      - 8080:80

  # The Database
  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/dbdata:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_USER: 'laravel'
          MYSQL_PASSWORD: 'secret'
          MYSQL_DATABASE: 'laravel'
    ports:
        - "3306:3306"

volumes:
  dbdata:
  my.cnf:
